source :rubygems

group :development do
  gem "unicorn"
  gem 'ruby-debug19', :require => 'ruby-debug'
end

group :test do
  gem "rails", "3.2.1"
  gem "newsly", :path => '../../'
  gem "letter_opener"
  gem "spork"
  gem "sqlite3"
  gem "rspec-rails"
  gem "capybara"
  gem "capybara-webkit"
  gem "database_cleaner"
  gem "rake"
end